### ISSUE TITLE
kubecontext locked into EKS shortening after recent update

### ISSUE THREAD

**Issue by patrickdean** [romkatv/powerlevel10k#142]
Relevant pl9k/pl10k config:
``` bash
ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context kubecontext dir virtualenv aws vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(battery)

POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
```

Relevant kubecontext:
``` yaml
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:DEVL_ACCOUNT_NUMBER:cluster/mycluster
    user: arn:aws:eks:us-east-1:DEVL_ACCOUNT_NUMBER:cluster/mycluster
  name: devl
- context:
    cluster: arn:aws:eks:us-east-1:PROD_ACCOUNT_NUMBER:cluster/mycluster
    user: arn:aws:eks:us-east-1:PROD_ACCOUNT_NUMBER:cluster/mycluster
  name: prod
current-context: devl
```

expected prompt:
patrick > ⎈ devl/default > ~ >  

actual prompt
patrick > ⎈ mycluster > ~ >  

When checking out commit: 63f72c7 it is working as expected. After introducing these cloud cluster shortening in 5bcbee9, it no longer uses the current-context/namespace.
