### ISSUE TITLE
kubecontext no change (microk8s)

### ISSUE THREAD

**Issue by huang12zheng** [romkatv/powerlevel10k#1489]
# describle
1. It looks like kubecontext gets its value from `$HOME/.kube/config` 
2. kubectl in microk8s would not change `$HOME/.kube/config`

It could be the same thing as  https://github.com/romkatv/powerlevel10k/issues/707
He's Docker and I'm Snap

# some test
```
# change namespace
❯ /usr/local/bin/kubens
Context "microk8s" modified.
Active namespace is "kube-node-lease".
 ~ ······························································································ microk8s/kube-public ○  k@ubuntu  11:45:36 PM ─
```
```
# notice that kubectl  is  snap alias microk8s.kubectl kubectl
# there are namespace: kube-node-lease   <<<<<<<<<<<<<<<<<<<<<<<
# but $HOME/.kube/config is no change
❯ kubectl config view -o=yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    namespace: kube-node-lease
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: REDACTED
 ~ ······························································································ microk8s/kube-public ○  k@ubuntu  11:45:36 PM ─
```
```
❯ whence kubectl
/snap/bin/kubectl

## change $HOME/.kube/config (which is old, namespace: is none)
 ~ ·························································································· microk8s/kube-node-lease ○  k@ubuntu  11:46:30 PM ─
```

-----------------------------------

`**********************`
-----------------------------------

* some question that It has nothing to do with issue:
https://github.com/huang12zheng/powerlevel10k/blob/1e7be00e04a6e34bdcc7574297413fd6a48be51f/internal/p10k.zsh#L4410-L4424

```
        for ((; pos > 0; --pos)); do
          local line=$cfg[pos]
          if [[ $line == '- context:' ]]; then
            return 0
          elif [[ $line == (#b)'    cluster: '($~str) ]]; then
            cluster=$match[1]
            [[ $cluster == $~qstr ]] && cluster=$cluster[2,-2]
          elif [[ $line == (#b)'    namespace: '($~str) ]]; then
            namespace=$match[1]
            [[ $namespace == $~qstr ]] && namespace=$namespace[2,-2]
          elif [[ $line == (#b)'    user: '($~str) ]]; then
            user=$match[1]
            [[ $user == $~qstr ]] && user=$user[2,-2]
          fi
        done
```

```
ubuntu% echo $cfg                                                                      
apiVersion: v1 clusters: - cluster:     certificate-authority-data: DATA+OMITTED     server: https://127.0.0.1:16443   name: microk8s-cluster contexts: - context:     cluster: microk8s-cluster     namespace: kube-node-lease     user: admin   name: microk8s current-context: microk8s kind: Config preferences: {} users: - name: admin   user:     token: REDACTED
```
```
ubuntu% echo $name                                                                     
microk8s
```
```
ubuntu% for ((; pos > 0; --pos)); do
          local line=$cfg[pos]
          if [[ $line == '- context:' ]]; then
            return 0
          elif [[ $line == (#b)'    cluster: '($~str) ]]; then
            cluster=$match[1]
            [[ $cluster == $~qstr ]] && cluster=$cluster[2,-2]
          elif [[ $line == (#b)'    namespace: '($~str) ]]; then
            namespace=$match[1]
            [[ $namespace == $~qstr ]] && namespace=$namespace[2,-2]
          elif [[ $line == (#b)'    user: '($~str) ]]; then
            user=$match[1]
            [[ $user == $~qstr ]] && user=$user[2,-2]
          fi
        done
ubuntu% echo "$cluster $name $namespace $user"
 microk8s  
```

* I see that it doesn't get the value, so what's going on here?
thanks.
