### ISSUE TITLE
Kubecontext not displaying via show on command

### ISSUE THREAD

**Issue by jhalterman** [romkatv/powerlevel10k#2258]
I have a vanilla 1.17 powerlevel10k install that I configured using the wizard, and for some reason kubecontext does not display for me via the show on command feature. Are there compatibility limitations with that feature or anything else to know about that might cause it to not work out of the box?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
(
  emulate zsh -o xtrace
  typeset -pm 'KUBECONFIG|HOME'
  : ${commands[kubectl]}
  which kubectl
  kubectl config view -o=yaml
)
```

**Comment by jhalterman** [comment]
```
+-zsh:10> typeset -pm 'KUBECONFIG|HOME'
export HOME=/Users/jonathan
+-zsh:11> : /usr/local/bin/kubectl
+-zsh:12> which kubectl
kubectl: aliased to kubecolor
+-zsh:13> kubecolor config view '-o=yaml'
apiVersion: v1
clusters: null
contexts:
- context:
    cluster: ""
    user: ""
  name: default
current-context: default
kind: Config
preferences: {}
users: null
```
