### ISSUE TITLE
git status behavior from starship

### ISSUE THREAD

**Issue by amogus07** [romkatv/powerlevel10k#2526]
I've been using starship, but since I only use zsh and p10k is specifically designed for it, I decided to give it a try. However, there's one thing I miss from starship, that being separate indicators for added, renamed and deleted files. This is my configuration for the git_status module of starship:
```toml
[git_status]
format = "[[$conflicted](yellow)[$untracked](218)[$modified$renamed](255)[$staged](green)[$deleted](red)($ahead_behind$stashed)]($style)"
conflicted = " $count "
untracked = " $count "
modified = " $count "
deleted = " $count "
staged = " $count "
renamed = " $count "
stashed = " $count "
style = "cyan"
```
This is an example of starship's behaviour:
```
  example 
❯ :> example
  example  1 
❯ ga example               
  ╰─> forgit::add example
A  example
  example  1 
❯ git commit -m "add example"                   
[master (root-commit) 6556e59] add example
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 example
  example 
❯ git mv example renamed-example
  example  1 
❯ rm renamed-example 
  example  1  1 
❯
```
This is what the same sequence looks like in p10k with some customization:
```
  ~/src/example    master 
❯ :> example
  ~/src/example    master  1 
❯ ga example
  ╰─> forgit::add example
A  example
  ~/src/example    master  1 
❯ git commit -m "add example"
[master (root-commit) 1931858] add example
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 example
  ~/src/example    master 
❯ git mv example renamed-example
  ~/src/example    master  2 
❯ rm renamed-example
  ~/src/example    master  2  1 
❯ 
```
As you can see, renamed and deleted files aren't recognized properly and instead show up as modified. Is it possible to get p10k to behave like starship in this example? Or am I missing something?
