### ISSUE TITLE
Update font installation for Alacritty

### ISSUE THREAD

**Issue by opixelum** [romkatv/powerlevel10k#2539]
Alacritty YAML config is deprecated. It uses TOML now. Update the instructions for installing the MesloLGS NF font for Alacritty.

Current:

- **Alacritty**: Create or open `~/.config/alacritty/alacritty.yml` and add the following section to it:
```yaml
font:
  normal:
    family: "MesloLGS NF"
```
     
New:

- **Alacritty**: Create or open `~/.config/alacritty/alacritty.toml` and add the following section to it:
```toml
[font.normal]
family = "MesloLGS NF"
```
