### ISSUE TITLE
Get rid of "[powerlevel10k] fetching gitstatusd .." initial mesg?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#747]
I get this mesg only one time in a new system. You can think it's not much because it do only one time, but I spin and destroy multiple systems at a time, and every time spin up a new system, I have to wait seconds for it to initialize.

Is there a way to get rid of this process or bundle it directly in source code?

**Comment by romkatv** [comment]
If you enable `vcs` prompt segment and don't define `POWERLEVEL9K_DISABLE_GITSTATUS=true`, Powerlevel10k will initialize [gitstatus](https://github.com/romkatv/gitstatus) on startup. When gitstatus initializes, it looks for the appropriate `gitstatusd` binary in `${GITSTATUS_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/gitstatus}`. If not found, it downloads the binary and stores it in the same directory. The message "fetching gitstatusd" indicates that `gitstatusd` is being downloaded.

Does this answer your question?

**Comment by tmpm697** [comment]
Yes, thanks, I'll copy `gitstatusd` binary into vms, so initiation won't echo mesg.

**Comment by BeakBryno7** [comment]
@romkatv I don't understand how to put the binary. Can you explain please?

**Comment by romkatv** [comment]
> @romkatv I don't understand how to put the binary. Can you explain please?

I don’t understand what you are asking. Can you clarify?

**Comment by tmpm697** [comment]
@BeakBryno7 : check `/home/user/.cache/gitstatus/gitstatusd-linux-x86_64`

**Comment by keyb0ardninja** [comment]
@romkatv I mount a `tmpfs` partition (RAM) to my `~/.cache` directory. This means the `~/.cache` directory is cleared after every reboot.

Is it possible to point the `gitstatusd` binary to a different location?

**Comment by romkatv** [comment]
@keyb0ardninja Please open another issue and copy your comment in it. I'll be happy to answer it.

**Comment by sebastienmascha** [comment]
As this plugin is enabled by default, should the `.cache/gitstatus/gitstatusd-linux-x86_64` be included in Powerlevel10k binary or oh-my-zsh binary?

**Comment by romkatv** [comment]
> As this plugin is enabled by default

Which plugin is enabled by default and where?

> should the `.cache/gitstatus/gitstatusd-linux-x86_64` be included in Powerlevel10k binary or oh-my-zsh binary?

What do you mean by Powerlevel10k binary and oh-my-zsh binary?

**Comment by vcapra1** [comment]
There is something wrong here.  I have the binary in $HOME/.cache, but I still get the message every time.  Git status works fine but I have to wait like 60 seconds every time I open a terminal while it tries, for whatever reason, to re-download gitstatusd.  

Latest release version of zsh and p10k

**Comment by romkatv** [comment]
@vcapra1 Please open a separate issue and supply as much info as you can.

**Comment by sebastienmascha** [comment]
> > As this plugin is enabled by default
> 
> Which plugin is enabled by default and where?
> 
> > should the `.cache/gitstatus/gitstatusd-linux-x86_64` be included in Powerlevel10k binary or oh-my-zsh binary?
> 
> What do you mean by Powerlevel10k binary and oh-my-zsh binary?

Sorry I misunderstood the goal of https://github.com/romkatv/gitstatus.
I was confused because with `POWERLEVEL9K_DISABLE_GITSTATUS=true` I was able to see the git status with powerlevel10k. I now understand that https://github.com/romkatv/gitstatus is a faster way to have git status output.

**Comment by arnovdk** [comment]
So, maybe the following isn't useful anymore, but I experienced a similar scenario as the topic starter and I'd been looking to automatically setup the gitstatus plugin during provisioning (using Ansible), so that I don't have to wait a couple of seconds, the first time I login, after installation of powerlevel10k.

My solution is to simply execute the script: `$HOME/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install`

My scenario is that I setup a couple of accounts for using the terminal (zsh / oh-my-zsh / powerlevel10k) and I wanted to setup the gitstatus plugin automatically for each of these accounts. Calling said script solved it for me.

Sample Ansible task:
```
- name: 'setting up plugin gitstatus for {{ user.name }}'
  ansible.builtin.command: "/bin/sh {{ item.home }}/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install"
  become_user: "{{ item.name }}"
  with_items:
    - name: root
      home: /root
    - name: xyz
      home: /home/xyz
    - name: abc
      home: /home/abc
```

**Comment by romkatv** [comment]
@arnovdk That works. If you want it to be future-proof, use `echo exit | script -qec zsh /dev/null >/dev/null`. This is equivalent to starting `zsh` and running `exit`. It'll allow powerlevel10k to do everything it needs to do on first run.

**Comment by arnovdk** [comment]
@romkatv , thanks a bunch for the tip. I tried it out and I was able to make it work, though I had to make a slight adjustment for my Ansible playbook.

For anyone that's interested, the new version of my example looks like this:
```
- name: 'setting up plugin gitstatus for {{ item.name }}'
  ansible.builtin.shell: "echo exit | script -qec zsh /dev/null >/dev/null"
  become_user: "{{ item.name }}"
  ignore_errors: yes # Not sure yet why Ansible generates an error on this task, but ignoring it solves it
  with_items:
    - name: root
      home: /root
    - name: xyz
      home: /home/xyz
    - name: abc
      home: /home/abc
```

As the comment in the above example states, this Ansible task generated an error for me, though I'm not sure yet why. I might look into it some more later. Anyways, ignoring the error solved it and yielded me the desired result: after logging in for the first time with one of the listed accounts, there's no delay anymore, because gitstatus is already available.

(Obviously, assume there's a preceding task that changes the default shell to zsh.)
